// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAllFlashcards():Promise<main.FlashcardMap>;

export function GetAllKanbanCards():Promise<Array<main.KanbanCard>>;

export function GetCurrentDateString():Promise<string>;

export function GetReviewCards():Promise<Array<main.Flashcard>>;

export function GetSettings():Promise<main.AppSettings>;

export function LoadConfig():Promise<void>;

export function NewConfig():Promise<void>;

export function PushAndSaveKanbanCard(arg1:string,arg2:string):Promise<number>;

export function ReviewCard(arg1:number,arg2:number):Promise<main.Flashcard>;

export function SaveConfig(arg1:main.AppSettings):Promise<void>;

export function SaveFlashcard(arg1:string,arg2:string):Promise<main.Flashcard>;
