// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllFlashcards() {
  return window['go']['main']['App']['GetAllFlashcards']();
}

export function GetCurrentDateString() {
  return window['go']['main']['App']['GetCurrentDateString']();
}

export function GetKanbanCards() {
  return window['go']['main']['App']['GetKanbanCards']();
}

export function GetKanbanColumns() {
  return window['go']['main']['App']['GetKanbanColumns']();
}

export function GetReviewCards() {
  return window['go']['main']['App']['GetReviewCards']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function NewConfig() {
  return window['go']['main']['App']['NewConfig']();
}

export function ReviewCard(arg1, arg2) {
  return window['go']['main']['App']['ReviewCard'](arg1, arg2);
}

export function SaveAllKanbanData(arg1, arg2) {
  return window['go']['main']['App']['SaveAllKanbanData'](arg1, arg2);
}

export function SaveColumn(arg1) {
  return window['go']['main']['App']['SaveColumn'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveFlashcard(arg1, arg2) {
  return window['go']['main']['App']['SaveFlashcard'](arg1, arg2);
}

export function SaveKanbanCard(arg1, arg2) {
  return window['go']['main']['App']['SaveKanbanCard'](arg1, arg2);
}
